### ISSUE TITLE
echo-federation won't run on macOS

### ISSUE THREAD

**Issue by cuihantao** [GMLC-TDC/helics-runner#3]
I installed HELICS on macOS 10.13.6 using Homebrew an installed helics-runner in Miniconda with Python 3.6. Then I tried to run the example, but it emits an error message

```
cuimac:helics-runner hcui7$ helics setup --path examples/echo-federation

cuimac:helics-runner hcui7$ helics validate --path examples/echo-federation/config.json
Traceback (most recent call last):
  File "/usr/local/miniconda3/bin/helics", line 11, in <module>
    load_entry_point('helics-runner', 'console_scripts', 'helics')()
  File "/usr/local/miniconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/miniconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/hcui7/repos/helics-runner/helics_runner/cli.py", line 187, in validate
    assert set(list(config.keys())) == set(["name", "broker", "federates"]), "Missing or additional keys found in config.json"
AssertionError: Missing or additional keys found in config.json
```

Please advise for debugging. Thanks.

**Comment by kdheepak** [comment]
Setup creates an example federation. Can you try running it without validation? I'll fix the validation, I think i know what the issue here is.

**Comment by cuihantao** [comment]
Well, no, I encountered a KeyError as follows:

```
cuimac:helics-runner hcui7$ helics run --path examples/echo-federation/config.json
Running federation: HELICSFederation
Traceback (most recent call last):
  File "/usr/local/miniconda3/bin/helics", line 11, in <module>
    load_entry_point('helics-runner', 'console_scripts', 'helics')()
  File "/usr/local/miniconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/miniconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/hcui7/repos/helics-runner/helics_runner/cli.py", line 110, in run
    if config["broker"] is True:
KeyError: 'broker'
```

**Comment by kdheepak** [comment]
The documentation for this helics cli needs to be improved. 

1) The following creates a folder called `HELICSFederation` with a `config.json` file in it.

```
$  helics setup --path examples/echo-federation
```

2) The following runs validation on the `config.json`.

```
$ helics validate --path examples/echo-federation/HELICSFederation/config.json
 - Valid keys in config.json
     - Valid keys in federate Federate1
     - Valid keys in federate Federate2
```

3) Copy the two federates into the folder.

```
$ cp examples/echo-federation/federate1.py examples/echo-federation/federate2.py examples/echo-federation/HELICSFederation/
```

4) Run the federation

```
$ helics run --path examples/echo-federation/HELICSFederation/config.json
Running federation: HELICSFederation
Running federate Federate1 as a background process
Running federate Federate2 as a background process
Waiting for 3 processes to finish ...
Done!

```

<img width="1680" alt="screen shot 2018-09-26 at 1 56 10 pm" src="https://user-images.githubusercontent.com/1813121/46105772-25e6bf80-c194-11e8-84a6-6bdf817cbafe.png">

**Comment by cuihantao** [comment]
The latest run commands work.
